# Generated by Django 5.0.7 on 2024-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('published', 'PUBLISHED'), ('expired', 'EXPIRED')], default='draft', max_length=20),
        ),
    ]
